---
language: go
go:
  - "1.13.4"

matrix:
  include:

    - os: linux
      services: docker
      script:
        - docker build -t archtest .

notifications:
  slack: fubarhouse:upHoIzmKb4ikkBOt2cOwgKXY